version: '3.8'
services:
  postgres:
    image: postgres:16.1-alpine3.19
    deploy:
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env.production
    ports:
      - 3333:3000
    depends_on:
      - postgres
    deploy:
      restart_policy:
        condition: on-failure
