version: '3.8'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  redis:
    image: redis:latest
    ports:
      - 6379:6379

  backend:
    build:
      dockerfile: Dockerfile
      context: .
      # Only will build development stage from our dockerfile
      target: development
    volumes:
      - ./src:/user/src/app/src
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: yarn start:dev
    ports:
      - 3333:3000
    depends_on:
      - postgres
      - redis
