apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
data:
  APP_NAME: "TECH_CHALLENGE"
  APP_PORT: "3000"
  NODE_ENV: "production"
  REDIS_CONNECTION_STRING: "localhost:6379"
  DATABASE_HOST: "main-db-service"
  DATABASE_PORT: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
      name: main-db-port
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
      name: api-pod
    spec:
      containers:
        - name: api-container
          image: cviniciussdias/grupo52:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: /liveness
            periodSeconds: 30
            initialDelaySeconds: 10
            failureThreshold: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 3000
              path: /hc
            periodSeconds: 10
            initialDelaySeconds: 10
            failureThreshold: 3
            successThreshold: 2
            timeoutSeconds: 1
          env:
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_USER
                  name: main-db-credentials
            - name: DATABASE_PASS
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_PASSWORD
                  name: main-db-credentials
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  key: POSTGRES_DB
                  name: main-db-credentials
          envFrom:
            - configMapRef:
                name: api-configmap
