name: Criar e publicar imagem docker
on:
  push:
    branches: [ "main" ]

env:
  EKS_CLUSTER_NAME: fiap-cluster
  AWS_REGION: us-east-1
jobs:
  deploy_on_eks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fazer login no Docker Hub
        run: docker login -u cviniciussdias -p ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Extrair versão da tag
        id: extract_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

      - name: Build da imagem docker
        run: docker build -t cviniciussdias/grupo52:latest --target production .

      - name: Push da imagem docker
        run: docker push cviniciussdias/grupo52:latest

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Update kube config
        run: aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Set DB credentials secret
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sed -i 's/{{DB_PASSWORD}}/"$DB_PASSWORD"/g; s/{{DB_USER}}/${{ secrets.DB_USERNAME }}/g' k8s/main-db-credentials-secret.yaml

      - name: Aplicar alterações do k8s
        run: kubectl apply -f k8s/